name: flutter_fiveflix
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0  
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/symbol.png
    - assets/images/gameGuessTheMovie.png
    - assets/images/profile.jpg
    - assets/images/loading.gif
    - assets/images/winner.gif
    - assets/images/loser.gif
    - assets/images/top10.png

  fonts:
    - family: NetflixSans
      fonts:
        - asset: assets/fonts/NetflixSans-Regular.otf
        - asset: assets/fonts/NetflixSans-Bold.otf
          weight: 700
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Regular.ttf
          weight: 700
